"""
Prediction Card Generator - Creates shareable image cards for match predictions.
"""

from PIL import Image, ImageDraw, ImageFont
import io


def create_prediction_card(player1, player2, winner, confidence, score_margin, player1_prob, player2_prob):
    """
    Create a shareable prediction card image.
    
    Args:
        player1: Name of player/team 1
        player2: Name of player/team 2
        winner: Predicted winner name
        confidence: Confidence percentage (0-100)
        score_margin: Predicted margin (positive = player1 wins by X, negative = player2 wins by X)
        player1_prob: Win probability for player 1 (0-1)
        player2_prob: Win probability for player 2 (0-1)
    
    Returns:
        BytesIO object containing the PNG image
    """
    width = 800
    height = 500
    
    card = Image.new('RGB', (width, height), color='#1a1a2e')
    draw = ImageDraw.Draw(card)
    
    try:
        title_font = ImageFont.truetype("arial.ttf", 36)
        name_font = ImageFont.truetype("arial.ttf", 28)
        stat_font = ImageFont.truetype("arial.ttf", 22)
        small_font = ImageFont.truetype("arial.ttf", 18)
    except:
        title_font = ImageFont.load_default()
        name_font = ImageFont.load_default()
        stat_font = ImageFont.load_default()
        small_font = ImageFont.load_default()
    
    draw.rectangle([(20, 20), (width-20, height-20)], outline='#16213e', width=3)
    
    title = "1v1Metrics Prediction"
    title_bbox = draw.textbbox((0, 0), title, font=title_font)
    title_width = title_bbox[2] - title_bbox[0]
    draw.text(((width - title_width) // 2, 40), title, fill='#e94560', font=title_font)
    
    draw.line([(40, 90), (width-40, 90)], fill='#16213e', width=2)
    
    player1_color = '#4ecca3' if winner == player1 else '#aaaaaa'
    player2_color = '#4ecca3' if winner == player2 else '#aaaaaa'
    
    p1_x = 100
    p2_x = width - 300
    
    p1_name_bbox = draw.textbbox((0, 0), player1[:15], font=name_font)
    p1_name_width = p1_name_bbox[2] - p1_name_bbox[0]
    draw.text((p1_x, 120), player1[:15], fill=player1_color, font=name_font)
    
    vs_text = "VS"
    vs_bbox = draw.textbbox((0, 0), vs_text, font=name_font)
    vs_width = vs_bbox[2] - vs_bbox[0]
    draw.text(((width - vs_width) // 2, 125), vs_text, fill='#e94560', font=name_font)
    
    p2_name_bbox = draw.textbbox((0, 0), player2[:15], font=name_font)
    p2_name_width = p2_name_bbox[2] - p2_name_bbox[0]
    draw.text((p2_x, 120), player2[:15], fill=player2_color, font=name_font)
    
    bar_y = 180
    bar_height = 30
    bar_x = 100
    bar_width = width - 200
    
    draw.rectangle([(bar_x, bar_y), (bar_x + bar_width, bar_y + bar_height)], fill='#16213e')
    
    p1_bar_width = int(bar_width * player1_prob)
    if p1_bar_width > 0:
        draw.rectangle([(bar_x, bar_y), (bar_x + p1_bar_width, bar_y + bar_height)], fill='#4ecca3')
    
    p1_prob_text = f"{player1_prob*100:.1f}%"
    p2_prob_text = f"{player2_prob*100:.1f}%"
    
    draw.text((bar_x + 10, bar_y + 5), p1_prob_text, fill='#1a1a2e', font=stat_font)
    p2_bbox = draw.textbbox((0, 0), p2_prob_text, font=stat_font)
    draw.text((bar_x + bar_width - p2_bbox[2] - 10, bar_y + 5), p2_prob_text, fill='#ffffff', font=stat_font)
    
    winner_text = f"Prediction: {winner}"
    winner_bbox = draw.textbbox((0, 0), winner_text, font=name_font)
    winner_width = winner_bbox[2] - winner_bbox[0]
    draw.text(((width - winner_width) // 2, 250), winner_text, fill='#4ecca3', font=name_font)
    
    conf_text = f"Confidence: {confidence:.1f}%"
    conf_bbox = draw.textbbox((0, 0), conf_text, font=stat_font)
    conf_width = conf_bbox[2] - conf_bbox[0]
    draw.text(((width - conf_width) // 2, 300), conf_text, fill='#aaaaaa', font=stat_font)
    
    if score_margin > 0:
        margin_text = f"{player1} wins by {abs(score_margin):.1f} points"
    elif score_margin < 0:
        margin_text = f"{player2} wins by {abs(score_margin):.1f} points"
    else:
        margin_text = "Expected to be close"
    
    margin_bbox = draw.textbbox((0, 0), margin_text, font=stat_font)
    margin_width = margin_bbox[2] - margin_bbox[0]
    draw.text(((width - margin_width) // 2, 340), margin_text, fill='#e94560', font=stat_font)
    
    draw.line([(40, 400), (width-40, 400)], fill='#16213e', width=2)
    
    footer = "Generated by 1v1Metrics"
    footer_bbox = draw.textbbox((0, 0), footer, font=small_font)
    footer_width = footer_bbox[2] - footer_bbox[0]
    draw.text(((width - footer_width) // 2, 420), footer, fill='#666666', font=small_font)
    
    img_buffer = io.BytesIO()
    card.save(img_buffer, format='PNG', quality=95)
    img_buffer.seek(0)
    
    return img_buffer


def create_matchup_card(player1, player2, p1_wins, p2_wins, total_matches, leader):
    """
    Create a shareable matchup card image for head-to-head history.
    """
    width = 800
    height = 450
    
    card = Image.new('RGB', (width, height), color='#1a1a2e')
    draw = ImageDraw.Draw(card)
    
    try:
        title_font = ImageFont.truetype("arial.ttf", 32)
        name_font = ImageFont.truetype("arial.ttf", 26)
        stat_font = ImageFont.truetype("arial.ttf", 22)
    except:
        title_font = ImageFont.load_default()
        name_font = ImageFont.load_default()
        stat_font = ImageFont.load_default()
    
    draw.rectangle([(20, 20), (width-20, height-20)], outline='#16213e', width=3)
    
    title = "1v1Metrics Head-to-Head"
    title_bbox = draw.textbbox((0, 0), title, font=title_font)
    title_width = title_bbox[2] - title_bbox[0]
    draw.text(((width - title_width) // 2, 35), title, fill='#e94560', font=title_font)
    
    draw.line([(40, 80), (width-40, 80)], fill='#16213e', width=2)
    
    p1_color = '#4ecca3' if leader == player1 else '#aaaaaa'
    p2_color = '#4ecca3' if leader == player2 else '#aaaaaa'
    if leader == "Tied":
        p1_color = p2_color = '#4ecca3'
    
    p1_x = 100
    p2_x = width - 250
    
    draw.text((p1_x, 100), player1[:18], fill=p1_color, font=name_font)
    draw.text((p2_x, 100), player2[:18], fill=p2_color, font=name_font)
    
    vs_text = "VS"
    vs_bbox = draw.textbbox((0, 0), vs_text, font=name_font)
    vs_width = vs_bbox[2] - vs_bbox[0]
    draw.text(((width - vs_width) // 2, 105), vs_text, fill='#e94560', font=name_font)
    
    score_y = 160
    p1_score_text = str(p1_wins)
    p2_score_text = str(p2_wins)
    
    p1_score_bbox = draw.textbbox((0, 0), p1_score_text, font=title_font)
    p1_score_width = p1_score_bbox[2] - p1_score_bbox[0]
    draw.text((p1_x + 50, score_y), p1_score_text, fill=p1_color, font=title_font)
    
    p2_score_bbox = draw.textbbox((0, 0), p2_score_text, font=title_font)
    p2_score_width = p2_score_bbox[2] - p2_score_bbox[0]
    draw.text((p2_x + 50, score_y), p2_score_text, fill=p2_color, font=title_font)
    
    dash_text = "-"
    dash_bbox = draw.textbbox((0, 0), dash_text, font=title_font)
    dash_width = dash_bbox[2] - dash_bbox[0]
    draw.text(((width - dash_width) // 2, score_y), dash_text, fill='#aaaaaa', font=title_font)
    
    total_text = f"{total_matches} total matches"
    total_bbox = draw.textbbox((0, 0), total_text, font=stat_font)
    total_width = total_bbox[2] - total_bbox[0]
    draw.text(((width - total_width) // 2, 240), total_text, fill='#aaaaaa', font=stat_font)
    
    if leader != "Tied":
        lead_text = f"{leader} leads"
    else:
        lead_text = "Series tied"
    
    lead_bbox = draw.textbbox((0, 0), lead_text, font=name_font)
    lead_width = lead_bbox[2] - lead_bbox[0]
    draw.text(((width - lead_width) // 2, 290), lead_text, fill='#4ecca3', font=name_font)
    
    draw.line([(40, 350), (width-40, 350)], fill='#16213e', width=2)
    
    footer = "Generated by 1v1Metrics"
    footer_bbox = draw.textbbox((0, 0), footer, font=stat_font)
    footer_width = footer_bbox[2] - footer_bbox[0]
    draw.text(((width - footer_width) // 2, 370), footer, fill='#666666', font=stat_font)
    
    img_buffer = io.BytesIO()
    card.save(img_buffer, format='PNG', quality=95)
    img_buffer.seek(0)
    
    return img_buffer
